FROM openjdk:8-jdk-alpine
ARG CONFIG_FILE= /media/github/erp/erp-config-files/*.yml
COPY ${CONFIG_FILE} /media/github/erp/erp-config-files/
ARG JAR_FILE=target/*.jar
COPY ${JAR_FILE} app.jar
ENTRYPOINT ["java","-jar","/app.jar"]